apiVersion: v1
kind: Pod
metadata:
  name: my_dummy_pod
  labels:
    app: dummy_app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx

# kubectl create -f pod.yaml