apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: dXNlcm5hbWU= # dXNlcm5hbWU= is base64 encoded username
  mongo-password: cGFzc3dvcmQ= # cGFzc3dvcmQ= is base64 encoded password